### ISSUE TITLE
[BUG] Global

### ISSUE THREAD

**Issue by Wonder-A** [Warriors-Army/warriors-bot-v2#111]
**Description du bug**
Le bot n'accepte plus aucune commande après sa première commande.

**Pour reproduire**
Étapes de reproduction du bug :
1. N'importe quelle commande
2.  Aucune commande ne fonctionne

**Comportement observé**
Les commandes / clignotent et sont inutilisable, seul /help fonctionne 

**Screenshots**
[Pour vous aider à expliquer, n'hésitez pas à ajouter des screenshots.](https://cdn.discordapp.com/attachments/920070645793030204/927926480317607986/unknown.png)
https://cdn.discordapp.com/attachments/920070645793030204/927926676007038976/2022-01-04_15-06-51.mp4

**Comment by Mizari-W** [comment]
C'est pas ma faute, c'est un problème qui vient de Discord 🤷‍♂️
